# Generated by Django 3.1.1 on 2020-10-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=1024)),
                ('time', models.CharField(max_length=1024)),
                ('companyNews', models.CharField(max_length=1024)),
            ],
        ),
    ]
